name = "db-com"
main = "src/index.ts"
compatibility_date = "2023-08-23"
usage_model = "bundled"
env = { }

[triggers]
crons = [ ]

[unsafe]
  [[unsafe.bindings]]
  database_id = "516fc90b-9ff8-4482-a548-b6e5b438fe21"
  name = "DATABASE"
  type = "d1"
