name: Send Result to Telegram

on:
  workflow_run:
    workflows: ["Deploy to Cloudflare Worker"]  # 根据你的实际工作流程名称修改
    types:
      - completed

jobs:
  send_message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Send message to Telegram
      env:
        TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
        TG_CHAT_ID: ${{ secrets.TG_CHAT_ID }}
      run: |
        MESSAGE="${{ job.status }} - CF Worker Sample 部署结果"
        curl -s -X POST "https://api.telegram.org/bot$TG_BOT_TOKEN/sendMessage" \
          -d chat_id="$TG_CHAT_ID" \
          -d text="$MESSAGE"
